#!/bin/sh

case "$1" in
    "up")
        amixer -D pulse sset Master 1%+
    ;;
    "down")
        amixer -D pulse sset Master 1%-
    ;;
    *)
        echo "Unsupported: \"$1\""
        exit 1
esac