#!/bin/sh

# Set environment variables
export DISPLAY=:0.0

# Run any scripts found under xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Start keyring daemon
gnome-keyring-daemon --start --components=pkcs11 &

# Set keyboard settings
xset r rate 225 35

# Set touchpad settings
xinput set-prop 15 297 1
xinput set-prop 15 299 0

# Set background
feh --bg-fill /home/grufwub/Pictures/Wallpapers/10-7.png

# Launch!
dbus-launch --sh-syntax --exit-with-session /usr/local/bin/dwm
